### ISSUE TITLE
Why is there a clearPrice property in the bid object?

### ISSUE THREAD

**Issue by ghost** [Avocarrot/openrtb#38]
Hi, I just didn't find this property in the openrtb specification

**Comment by giorgosera** [comment]
This property is a `helper` property that, as you correctly pointed out, is not part of the protocol. Since this lib is used in the context of an exchange it's useful to maintain a `clearPrice` property on the object which is determined after the auction is completed. 

There are some other extra properties on the bid and bidResponse objects and they are documented [here](https://www.npmjs.com/package/openrtb#bid)
